#!/bin/bash
# enforce-git-workflow.sh — enforce docs/convention/git-workflow.md hard rules on Bash tool calls

INPUT=$(cat)
COMMAND=$(node -e 'let d="";process.stdin.on("data",c=>d+=c).on("end",()=>{try{process.stdout.write(JSON.parse(d).tool_input?.command||"")}catch{}})' <<< "$INPUT")

# Only care about commands that touch git commit/push
if [[ "$COMMAND" != *"git commit"* && "$COMMAND" != *"git push"* ]]; then
  exit 0
fi

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)

# 1) Never `git push --force` — only --force-with-lease is allowed
if [[ "$COMMAND" == *"git push"* ]] && [[ "$COMMAND" =~ (^|[[:space:]])--force([[:space:]]|=|$) ]] && [[ "$COMMAND" != *"--force-with-lease"* ]]; then
  echo "Blocked: use --force-with-lease instead of --force (docs/convention/git-workflow.md §5/§13)" >&2
  exit 2
fi

# 2) No direct commit/push while on a protected branch
if [[ "$CURRENT_BRANCH" == "main" || "$CURRENT_BRANCH" == "dev" ]]; then
  if [[ "$COMMAND" == *"git commit"* ]]; then
    echo "Blocked: direct commit to protected branch '$CURRENT_BRANCH' is not allowed — create a feature/fix/chore/docs branch from dev (docs/convention/git-workflow.md §13)" >&2
    exit 2
  fi
  if [[ "$COMMAND" == *"git push"* ]]; then
    echo "Blocked: direct push to protected branch '$CURRENT_BRANCH' is not allowed — open a Pull Request instead (docs/convention/git-workflow.md §13)" >&2
    exit 2
  fi
fi

# 3) No push to main/dev via explicit refspec, regardless of current branch
if [[ "$COMMAND" == *"git push"* ]] && [[ "$COMMAND" =~ (origin|upstream)[[:space:]]+(main|dev)([[:space:]:]|$) ]]; then
  echo "Blocked: direct push to protected branch via explicit refspec is not allowed — open a Pull Request instead (docs/convention/git-workflow.md §13)" >&2
  exit 2
fi

# 4) No AI attribution in commit messages (project convention overrides default attribution behavior)
if [[ "$COMMAND" == *"git commit"* ]] && echo "$COMMAND" | grep -Eqi "co-authored-by:[[:space:]]*(claude|chatgpt|gpt|ai)|generated by claude|ai-generated"; then
  echo "Blocked: commit message must not contain AI attribution (docs/convention/git-workflow.md §12) — remove Co-Authored-By/Generated-by lines" >&2
  exit 2
fi

exit 0
